name: ngajiyuk
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  chewie: ^1.0.0
  cloud_firestore: ^1.0.6
  collection: ^1.15.0-nullsafety.4
  cupertino_icons: ^1.0.2
  firebase_analytics: ^8.0.1
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  flutter_bloc: ^7.0.0
  flutter_dotenv: ^4.0.0-nullsafety.0
  freezed_annotation: ^0.14.1
  get_it: ^6.1.1
  google_sign_in: ^5.0.2
  injectable: ^1.2.2
  intl: ^0.17.0
  json_serializable: ^4.1.0
  package_info: ^2.0.0
  rxdart: ^0.26.0
  sentry_flutter: ^5.0.0
  url_launcher: ^6.0.3
  video_player: ^2.1.1
  youtube_player_iframe: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  freezed: ^0.14.1+2
  injectable_generator: ^1.2.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
